[filter]
barcode = "6-06949-34362-0"
# country = "XE"
date = "2002"

[rip]

[encode]

[flac]
compression_level = 8
cue_sheet = true

[template]
# dir = "{artist}/{album}"
# file = "{tracknum:02d} - {title}.{suffix}"
